create table if not exists public.sets (
  id text primary key,
  name text not null,
  era text not null,
  language text not null check (language in ('english', 'japanese')),
  release_year int,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

alter table public.sets enable row level security;

drop policy if exists "Allow read access to sets" on public.sets;
create policy "Allow read access to sets"
  on public.sets
  for select
  to anon
  using (true);

drop policy if exists "Allow service role to manage sets" on public.sets;
create policy "Allow service role to manage sets"
  on public.sets
  for all
  to service_role
  using (true)
  with check (true);

-- Seed English sets
insert into public.sets (id, name, era, language)
select concat('english-', lower(regexp_replace(name, '[^a-z0-9]+', '-', 'g'))) as id,
       name,
       era,
       'english'
from (values
  ('Mega Evolution', 'Mega Evolution'),
  ('Mega Evolution Promos', 'Mega Evolution'),
  ('White Flare', 'Scarlet & Violet'),
  ('Black Bolt', 'Scarlet & Violet'),
  ('Destined Rivals', 'Scarlet & Violet'),
  ('Journey Together', 'Scarlet & Violet'),
  ('McDonald''s Dragon Discovery', 'Scarlet & Violet'),
  ('Prismatic Evolutions', 'Scarlet & Violet'),
  ('Surging Sparks', 'Scarlet & Violet'),
  ('Stellar Crown', 'Scarlet & Violet'),
  ('Trick or Trade 2024', 'Scarlet & Violet'),
  ('Shrouded Fable', 'Scarlet & Violet'),
  ('Twilight Masquerade', 'Scarlet & Violet'),
  ('Temporal Forces', 'Scarlet & Violet'),
  ('Paldean Fates', 'Scarlet & Violet'),
  ('Paradox Rift', 'Scarlet & Violet'),
  ('Pokemon Card 151', 'Scarlet & Violet'),
  ('Trick or Trade 2023', 'Scarlet & Violet'),
  ('Obsidian Flames', 'Scarlet & Violet'),
  ('McDonald''s Promos 2023', 'Scarlet & Violet'),
  ('Paldea Evolved', 'Scarlet & Violet'),
  ('Scarlet & Violet Base', 'Scarlet & Violet'),
  ('Scarlet & Violet Promos', 'Scarlet & Violet'),
  ('Trading Card Game Classic', 'Sword & Shield'),
  ('Crown Zenith', 'Sword & Shield'),
  ('Silver Tempest', 'Sword & Shield'),
  ('Lost Origin', 'Sword & Shield'),
  ('Trick or Trade 2022', 'Sword & Shield'),
  ('McDonald''s Promos 2022', 'Sword & Shield'),
  ('Pokemon GO', 'Sword & Shield'),
  ('Astral Radiance', 'Sword & Shield'),
  ('Brilliant Stars', 'Sword & Shield'),
  ('Fusion Strike', 'Sword & Shield'),
  ('Celebrations', 'Sword & Shield'),
  ('Celebrations: Classic Collection', 'Sword & Shield'),
  ('Evolving Skies', 'Sword & Shield'),
  ('Chilling Reign', 'Sword & Shield'),
  ('Battle Styles', 'Sword & Shield'),
  ('Shining Fates', 'Sword & Shield'),
  ('McDonald''s 25th Anniversary', 'Sword & Shield'),
  ('Vivid Voltage', 'Sword & Shield'),
  ('Champion''s Path', 'Sword & Shield'),
  ('Darkness Ablaze', 'Sword & Shield'),
  ('Rebel Clash', 'Sword & Shield'),
  ('Sword & Shield', 'Sword & Shield'),
  ('Sword & Shield Promo', 'Sword & Shield'),
  ('Cosmic Eclipse', 'Sun & Moon'),
  ('McDonald''s Promos 2019', 'Sun & Moon'),
  ('Hidden Fates', 'Sun & Moon'),
  ('Unified Minds', 'Sun & Moon'),
  ('Unbroken Bonds', 'Sun & Moon'),
  ('Detective Pikachu', 'Sun & Moon'),
  ('Team Up', 'Sun & Moon'),
  ('Lost Thunder', 'Sun & Moon'),
  ('McDonald''s Promos 2018', 'Sun & Moon'),
  ('Dragon Majesty', 'Sun & Moon'),
  ('Celestial Storm', 'Sun & Moon'),
  ('Forbidden Light', 'Sun & Moon'),
  ('Ultra Prism', 'Sun & Moon'),
  ('Crimson Invasion', 'Sun & Moon'),
  ('Shining Legends', 'Sun & Moon'),
  ('Burning Shadows', 'Sun & Moon'),
  ('McDonald''s Promos 2017', 'Sun & Moon'),
  ('Guardians Rising', 'Sun & Moon'),
  ('Sun & Moon', 'Sun & Moon'),
  ('Sun & Moon Black Star Promo', 'Sun & Moon'),
  ('Evolutions', 'XY'),
  ('McDonald''s Promos 2016', 'XY'),
  ('Steam Siege', 'XY'),
  ('Fates Collide', 'XY'),
  ('Generations', 'XY'),
  ('Generations Radiant Collection', 'XY'),
  ('BREAKpoint', 'XY'),
  ('McDonald''s Promos 2015', 'XY'),
  ('BREAKthrough', 'XY'),
  ('Ancient Origins', 'XY'),
  ('Roaring Skies', 'XY'),
  ('Double Crisis', 'XY'),
  ('Primal Clash', 'XY'),
  ('Phantom Forces', 'XY'),
  ('Furious Fists', 'XY'),
  ('Alternate Art Promos', 'XY'),
  ('McDonald''s Promos 2014', 'XY'),
  ('Flashfire', 'XY'),
  ('XY Base', 'XY'),
  ('XY Black Star Promos', 'XY'),
  ('Legendary Treasures', 'Black & White'),
  ('Legendary Treasures Radiant Collection', 'Black & White'),
  ('Plasma Blast', 'Black & White'),
  ('Plasma Freeze', 'Black & White'),
  ('Plasma Storm', 'Black & White'),
  ('Dragon Vault', 'Black & White'),
  ('Boundaries Crossed', 'Black & White'),
  ('Dragons Exalted', 'Black & White'),
  ('McDonald''s Promos 2012', 'Black & White'),
  ('Dark Explorers', 'Black & White'),
  ('Next Destinies', 'Black & White'),
  ('Noble Victories', 'Black & White'),
  ('Emerging Powers', 'Black & White'),
  ('McDonald''s Promos 2011', 'Black & White'),
  ('Black and White', 'Black & White'),
  ('Black and White Promos', 'Black & White'),
  ('Call of Legends', 'Call of Legends'),
  ('Triumphant', 'HeartGold SoulSilver'),
  ('Undaunted', 'HeartGold SoulSilver'),
  ('Unleashed', 'HeartGold SoulSilver'),
  ('HeartGold SoulSilver', 'HeartGold SoulSilver'),
  ('HGSS Black Star Promo', 'HeartGold SoulSilver'),
  ('Miscellaneous Promos', 'HeartGold SoulSilver'),
  ('Pokemon Rumble', 'Platinum'),
  ('Arceus', 'Platinum'),
  ('Supreme Victors', 'Platinum'),
  ('Rising Rivals', 'Platinum'),
  ('Pop Series 9', 'Platinum'),
  ('Platinum', 'Platinum'),
  ('Stormfront', 'Diamond & Pearl'),
  ('Pop Series 8', 'Diamond & Pearl'),
  ('Legends Awakened', 'Diamond & Pearl'),
  ('Majestic Dawn', 'Diamond & Pearl'),
  ('Pop Series 7', 'Diamond & Pearl'),
  ('Great Encounters', 'Diamond & Pearl'),
  ('Secret Wonders', 'Diamond & Pearl'),
  ('Pop Series 6', 'Diamond & Pearl'),
  ('Mysterious Treasures', 'Diamond & Pearl'),
  ('Diamond & Pearl', 'Diamond & Pearl'),
  ('Diamond and Pearl Promo', 'Diamond & Pearl'),
  ('Pop Series 5', 'EX Ruby & Sapphire'),
  ('Power Keepers', 'EX Ruby & Sapphire'),
  ('Dragon Frontiers', 'EX Ruby & Sapphire'),
  ('Pop Series 4', 'EX Ruby & Sapphire'),
  ('Crystal Guardians', 'EX Ruby & Sapphire'),
  ('Holon Phantoms', 'EX Ruby & Sapphire'),
  ('Pop Series 3', 'EX Ruby & Sapphire'),
  ('Legend Maker', 'EX Ruby & Sapphire'),
  ('Delta Species', 'EX Ruby & Sapphire'),
  ('Unseen Forces', 'EX Ruby & Sapphire'),
  ('Pop Series 2', 'EX Ruby & Sapphire'),
  ('Emerald', 'EX Ruby & Sapphire'),
  ('Deoxys', 'EX Ruby & Sapphire'),
  ('Team Rocket Returns', 'EX Ruby & Sapphire'),
  ('Pop Series 1', 'EX Ruby & Sapphire'),
  ('Fire Red Leaf Green', 'EX Ruby & Sapphire'),
  ('Hidden Legends', 'EX Ruby & Sapphire'),
  ('Team Magma vs Team Aqua', 'EX Ruby & Sapphire'),
  ('Nintendo Black Star Promo', 'EX Ruby & Sapphire'),
  ('Sandstorm', 'EX Ruby & Sapphire'),
  ('Dragon', 'EX Ruby & Sapphire'),
  ('Ruby and Sapphire', 'EX Ruby & Sapphire'),
  ('Skyridge', 'e-Card'),
  ('Aquapolis', 'e-Card'),
  ('Expedition', 'e-Card'),
  ('Legendary Collection', 'Legendary Collection'),
  ('Neo Destiny', 'Neo'),
  ('Neo Revelation', 'Neo'),
  ('Southern Islands', 'Neo'),
  ('Neo Discovery', 'Neo'),
  ('Neo Genesis', 'Neo'),
  ('Neo Genesis 1st Edition', 'Neo'),
  ('Gym Challenge', 'Gym'),
  ('Gym Heroes', 'Gym'),
  ('Team Rocket', 'Base'),
  ('Base Set 2', 'Base'),
  ('Fossil', 'Base'),
  ('WOTC Promo', 'Base'),
  ('Jungle', 'Base'),
  ('Base Set Unlimited', 'Base'),
  ('Base Set Shadowless', 'Base'),
  ('Base Set', 'Base')
) as english_sets(name, era)
on conflict (id) do nothing;

-- Seed Japanese sets
insert into public.sets (id, name, era, language)
select concat('japanese-', lower(regexp_replace(name, '[^a-z0-9]+', '-', 'g'))) as id,
       name,
       era,
       'japanese'
from (values
  ('White Flare', 'Scarlet & Violet'),
  ('Black Bolt', 'Scarlet & Violet'),
  ('Night Wanderer', 'Scarlet & Violet'),
  ('Surging Sparks', 'Scarlet & Violet'),
  ('Stellar Crown', 'Scarlet & Violet'),
  ('Cyber Judge', 'Scarlet & Violet'),
  ('Wild Force', 'Scarlet & Violet'),
  ('Ancient Roar', 'Scarlet & Violet'),
  ('Future Flash', 'Scarlet & Violet'),
  ('Raging Surf', 'Scarlet & Violet'),
  ('Snow Hazard', 'Scarlet & Violet'),
  ('Clay Burst', 'Scarlet & Violet'),
  ('Triplet Beat', 'Scarlet & Violet'),
  ('Scarlet & Violet ex Starter Set', 'Scarlet & Violet'),
  ('Scarlet ex', 'Scarlet & Violet'),
  ('Violet ex', 'Scarlet & Violet'),
  ('Pokémon Card 151 (JP)', 'Scarlet & Violet'),
  ('Pokemon Card Gym Promo SV Series', 'Scarlet & Violet'),
  ('VSTAR Universe', 'Sword & Shield'),
  ('Paradigm Trigger', 'Sword & Shield'),
  ('Incandescent Arcana', 'Sword & Shield'),
  ('Lost Abyss', 'Sword & Shield'),
  ('Dark Phantasma', 'Sword & Shield'),
  ('Battle Region', 'Sword & Shield'),
  ('Star Birth', 'Sword & Shield'),
  ('Vmax Climax', 'Sword & Shield'),
  ('Fusion Arts', 'Sword & Shield'),
  ('Blue Sky Stream', 'Sword & Shield'),
  ('Skyscraping Perfect', 'Sword & Shield'),
  ('Eevee Heroes', 'Sword & Shield'),
  ('Silver Lance', 'Sword & Shield'),
  ('Jet-Black Spirit', 'Sword & Shield'),
  ('Matchless Fighters', 'Sword & Shield'),
  ('Single Strike Master', 'Sword & Shield'),
  ('Rapid Strike Master', 'Sword & Shield'),
  ('Shiny Star V', 'Sword & Shield'),
  ('Legendary Heartbeat', 'Sword & Shield'),
  ('Infinity Zone', 'Sword & Shield'),
  ('Explosive Walker', 'Sword & Shield'),
  ('Rebel Clash (JP: Rebellion Crash)', 'Sword & Shield'),
  ('Vmax Rising', 'Sword & Shield'),
  ('Sword', 'Sword & Shield'),
  ('Shield', 'Sword & Shield'),
  ('Pokemon Card Gym Promo S Series', 'Sword & Shield'),
  ('Dream League', 'Sun & Moon'),
  ('Alter Genesis', 'Sun & Moon'),
  ('Remix Bout', 'Sun & Moon'),
  ('Miracle Twins', 'Sun & Moon'),
  ('Sky Legend', 'Sun & Moon'),
  ('Double Blaze', 'Sun & Moon'),
  ('Full Metal Wall', 'Sun & Moon'),
  ('Night Unison', 'Sun & Moon'),
  ('Tag Team GX All Stars', 'Sun & Moon'),
  ('Ultra Shiny GX', 'Sun & Moon'),
  ('Hidden Fates (JP: GX Ultra Shiny Mini Sets)', 'Sun & Moon'),
  ('SM12a Tag All Stars', 'Sun & Moon'),
  ('Pokemon Card Gym Promo SM Series', 'Sun & Moon'),
  ('Premium Champion Pack', 'XY'),
  ('The Best of XY', 'XY'),
  ('Battle Festa 2015', 'XY'),
  ('Rage of the Broken Sky', 'XY'),
  ('Blue Shock', 'XY'),
  ('Red Flash', 'XY'),
  ('Emerald Break', 'XY'),
  ('Gaia Volcano', 'XY'),
  ('Rising Fist', 'XY'),
  ('Wild Blaze', 'XY'),
  ('Bandit Ring', 'XY'),
  ('Collection X', 'XY'),
  ('Collection Y', 'XY'),
  ('XY-P Promo', 'XY'),
  ('Legendary Treasures (JP: EX Battle Boost)', 'Black & White'),
  ('Shiny Collection', 'Black & White'),
  ('Mega Lillie''s Pokémon', 'Black & White'),
  ('Plasma Gale', 'Black & White'),
  ('Plasma Storm', 'Black & White'),
  ('Plasma Blast', 'Black & White'),
  ('Cold Flare', 'Black & White'),
  ('Dark Rush', 'Black & White'),
  ('Dragon Blade', 'Black & White'),
  ('Dragon Blast', 'Black & White'),
  ('PokeKyun Collection', 'Black & White'),
  ('BW-P Promo', 'Black & White'),
  ('DPt-P Promo', 'Diamond & Pearl'),
  ('Lost Link', 'Diamond & Pearl'),
  ('SoulSilver Collection', 'Diamond & Pearl'),
  ('HeartGold Collection', 'Diamond & Pearl'),
  ('Intense Fight in the Destroyed Sky', 'Diamond & Pearl'),
  ('Galactic''s Conquest', 'Diamond & Pearl'),
  ('Temple of Anger', 'Diamond & Pearl'),
  ('Cry from the Mysterious', 'Diamond & Pearl'),
  ('Awakening Legends', 'Diamond & Pearl'),
  ('DPBP# Series', 'Diamond & Pearl'),
  ('Expansion Pack', 'e-Card'),
  ('Pokedex Cards', 'e-Card'),
  ('Mysterious Mountains', 'e-Card'),
  ('Wind from the Sea', 'e-Card'),
  ('Split Earth', 'e-Card'),
  ('Town on No Map', 'e-Card'),
  ('Eevee Heroes (JP: Eevee Heroes Premium)', 'e-Card'),
  ('Vending Card Series', 'e-Card'),
  ('Neo Genesis (JP)', 'Neo'),
  ('Neo Discovery (JP)', 'Neo'),
  ('Neo Revelation (JP)', 'Neo'),
  ('Neo Destiny (JP)', 'Neo'),
  ('Gym Heroes (JP)', 'Gym'),
  ('Gym Challenge (JP)', 'Gym'),
  ('Expansion Pack (Base Set JP)', 'Base'),
  ('Jungle (JP)', 'Base'),
  ('Fossil (JP)', 'Base'),
  ('Team Rocket (JP)', 'Base'),
  ('Rocket Gang', 'Base'),
  ('Intro Pack Neo', 'Base')
) as japanese_sets(name, era)
on conflict (id) do nothing;
