// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://icuumgfjnjynbyqvzxwb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImljdXVtZ2Zqbmp5bmJ5cXZ6eHdiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjMyMDUyMDIsImV4cCI6MjA3ODc4MTIwMn0.AYre-WMHdgxY6HIlCGiaORMELrAsDnZlHXg_xo3EGu4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Note: redirectTo is set dynamically in authService.ts using window.location.origin
// This ensures redirects always use the current URL (localhost, softgen.dev, or production)
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    detectSessionInUrl: true,
    // redirectTo will be set per-request in authService.ts
  },
});
