// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xxsnsomathouvuhtshyw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh4c25zb21hdGhvdXZ1aHRzaHl3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjMwMzQ4MzgsImV4cCI6MjA3ODYxMDgzOH0.-WOedL2s0em5wkfW5TPCnb4fWonX0rD0yf8rbQ9cUfU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Note: redirectTo is set dynamically in authService.ts using window.location.origin
// This ensures redirects always use the current URL (localhost, softgen.dev, or production)
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    detectSessionInUrl: true,
    // redirectTo will be set per-request in authService.ts
  },
});
